name: CronJob
on:
  schedule:
    - cron: "10,40 * * * *" # ie. 4:10pm, 4:40pm, 5:10pm, etc.
  push:
env:
  DATA: ${{secrets.DATA}}
  OPTIMISM_SEPOLIA_RPC_URL: ${{secrets.OPTIMISM_SEPOLIA_RPC_URL}}
  NODE_OPTIONS: "--max_old_space_size=32768"
permissions: write-all
jobs:
  runCLI:
    name: Winners Compute
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["20.11.1"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Clone foundry-winner-calc repo
        uses: actions/checkout@master
        with:
          repository: GenerationSoftware/foundry-winner-calc
          path: './foundry-winner-calc'

      # -------------------------------------------------------- #
      # Optimism Sepolia
      # -------------------------------------------------------- #
      # 1. Install
      - name: Install PoolTogether V5 CLI
        run: |
          npm install -g @generationsoftware/pt-v5-cli@1.1.0-beta.2
          echo "$(npm -g bin)" >> $GITHUB_PATH
          
      # 2. Compute JSON input files (vault accounts)
      - name: Optimism Sepolia Vault Accounts
        id: vaultAccountsOptimismSepolia
        uses: chuckbergeron/executable-wrapper@f94b435740d6b958c2d7eb76c77657e761819cfe
        continue-on-error: true
        with:
          run_command: ptv5 compute vaultAccounts -o ./vaultAccounts -p 0x5e1b40e4249644a7d7589d1197AD0F1628e79FB1 -c 11155420

      # 3. Install package deps, build contracts
      - name: Install deps and run
        run: |
          cd ./foundry-winner-calc
          npm install
          npm run build
          cd sol
          forge install
          forge build
          cd ..

      # 4. Loop through vault input files, compute winners
      - name: Install deps and run
        run: |
          ls
          node index.js ./vaultAccounts/id.json ./vaultAccountOutputs/id.json
          cat example-output.json

      # # 5. Commit
      # - name: Commit Optimism Sepolia
      #   if: steps.vaultAccounts.outputs.runStatus == 'true'
      #   continue-on-error: true
      #   run: |
      #     git config pull.rebase false
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git pull
      #     git add ./prizes/11155420
      #     git commit -m "Add testnet draw for Optimism Sepolia draw #${{steps.vaultAccounts.outputs.drawId}}"
      # # 4. Push
      # - name: Push changes (if required)
      #   uses: ad-m/github-push-action@master
      #   if: steps.vaultAccounts.outputs.runStatus == 'true'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
      #     force: true
      # # -------------------------------------------------------- #
      # # Comment Error
      # # -------------------------------------------------------- #
      # - name: Comment Error
      #   id: commentError
      #   if: steps.vaultAccounts.outputs.exitcode == 1
      #   # if: steps.winnersArbitrumSepolia.outputs.exitcode == 1 || steps.vaultAccounts.outputs.exitcode == 1
      #   uses: actions/github-script@v5
      #   continue-on-error: true
      #   with:
      #     script: |
      #       await github.rest.issues.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         title: `Draw Prizes Failed: Exit Code 1`
      #       })
